### ISSUE TITLE
Front - Etusivun jatkokehitys joingame + ominaisuudet

### ISSUE THREAD

**Issue by SajariS** [SajariS/JuomaPeli#79]
Luo/kopioi joingame komponentista popup dialogi kun painetaan "liity" painiketta, sen sijaan että siirretään uuteen komponenttiin, avataan pop up dialogi jonne voi syöttää koodin, nimi annetaan aikaisemmassa inputissa.
Luo myös jonkinnäköinen ilmoitus käyttäjälle jos koodilla ei löydy peliä, eli käsittele mahdollinen virhe fetchissä

**Comment by Samwes13** [comment]
Popup toimii, mutta fontpage handlestrart fetch onglemia.

**Comment by SajariS** [comment]
Liittyminen toimii, koodin tarkastusta en ehtinyt tarkastamaan. Jatkokehitetään seuraavaan julkaisuun
